### ISSUE TITLE
Can't Run SVGWallpaper Demo

### ISSUE THREAD

**Issue by ffleandro** [pents90/svg-android#3]
I'm having trouble using your example project.
I followed the instructions, but can't run it.
Why do you have a Service instead of an Application?

Also, I can't use your code in my own project, everything goes well, except nothing shows in my ImageView.

**Comment by pents90** [comment]
If you are running on Android 4.x, you may need to turn off hardware acceleration to make it work. See http://stackoverflow.com/questions/10384613/android-canvas-drawpicture-not-working-in-devices-with-ice-cream-sandwich and http://stackoverflow.com/questions/8771219/android-4-0-compatibility-issues-with-canvas-clippath

**Comment by dsdsfga** [comment]
I fround a solution for this problem here: http://stackoverflow.com/a/13992014/995926

**Comment by ffleandro** [comment]
@dsdsfga as I explained on your stackoverflow question, by converting your `Picture` into a `Bitmap` is much more inefficient if you have large images and if you need to Zoom and Pan.

Instead I solved this issue by turning off hardware acceleration only on the view that will hold the `Picture` object.
For more details check my answer here: http://stackoverflow.com/a/14054331/596708
